# Generated by Django 6.0.3 on 2026-03-17 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Расписание', max_length=100, verbose_name='Название')),
                ('image', models.ImageField(upload_to='schedules/', verbose_name='Фото расписания')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('date', models.DateField(verbose_name='На какую дату')),
                ('is_active', models.BooleanField(default=True, verbose_name='Актуальное')),
            ],
            options={
                'verbose_name': 'Расписание',
                'verbose_name_plural': 'Расписания',
                'ordering': ['-date'],
            },
        ),
    ]
