# Generated by Django 6.0.3 on 2026-03-17 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='image',
        ),
        migrations.CreateModel(
            name='SchedulePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='schedules/', verbose_name='Фото страницы')),
                ('page_number', models.PositiveIntegerField(verbose_name='Номер страницы')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='main.schedule', verbose_name='Расписание')),
            ],
            options={
                'verbose_name': 'Страница расписания',
                'verbose_name_plural': 'Страницы расписания',
                'ordering': ['page_number'],
            },
        ),
    ]
